#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""schneider_robot_controller.robot_controller_node  --  V23

V20-V22 used hand-tuned joint poses. V22 admitted in its own resumen that
those poses were "not IK-validated" and that the gripper TCP did not end
on the CAFI. V22 then patched the grasp confirmation by ignoring TCP
geometry entirely ("task-aware grasp"), which is what produced the
teletransport-feel pick the user is now rejecting.

V23 removes that whole class of bugs at the root:

  - All operative poses are now resolved OFFLINE by damped-LS IK against
    the V20/V22 URDF chain (FK validated, see scripts/resolve_poses.py
    and validate_robot_poses.txt). Position error <= 0.1 mm for every
    pose. Each pose places the gripper grasp_center frame on the actual
    workpiece target in WORLD coordinates.
  - The pick-and-place sequence is split into approach -> pick -> close
    -> lift, with the GRIPPER_CLOSE only fired AFTER the arm reaches
    PICK and the controller WAITS for /gripper/grasp_confirmed before
    advancing to LIFT. If grasp_confirmed never fires the trajectory
    stalls and the state_manager watchdog reports it, instead of the
    arm secretly "picking" thin air and the CAFI snapping to follow.
  - Motion is interpolated in joint-space with a velocity cap so RViz
    shows the whole travel (1.6 rad/s -> ~2 s for the longest segment),
    not a teleport. Cosine-eased.
  - All 17 POSE_LIB entries come from scripts/resolved_poses.py, which
    in turn is regenerated by scripts/resolve_poses.py.  Do NOT hand-
    edit POSE_LIB here.
"""
import json
import math
import os
import sys
import threading

import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Bool, Empty, String


# ============================================================
# V33 JOINT NAMES (Cobot_URDFBUENO canonical URDF).
# The canonical URDF defines joint_1..joint_6 on the cobot base; the
# xacro wrapper in schneider_cell_description prefixes them with the
# instance name (lexium_cobot).  So the V33 system uses:
#     lexium_cobot_joint_1 .. lexium_cobot_joint_6
# Joint limits are taken straight from the canonical URDF.
# ============================================================
COBOT_JOINTS = ["lexium_cobot_joint_1", "lexium_cobot_joint_2",
                "lexium_cobot_joint_3", "lexium_cobot_joint_4",
                "lexium_cobot_joint_5", "lexium_cobot_joint_6"]

# Joint limits from the canonical URDF (Cobot_URDFBUENO.zip).
#   joint_1, joint_4, joint_6: +/-3.14159 rad (+/-180 deg)
#   joint_2, joint_3:          +/-2.61799 rad (+/-150 deg)
#   joint_5:                   +/-2.09440 rad (+/-120 deg)
J_LIMIT_LOW  = [-3.14159, -2.61799, -2.61799, -3.14159, -2.09440, -3.14159]
J_LIMIT_HIGH = [+3.14159, +2.61799, +2.61799, +3.14159, +2.09440, +3.14159]


# ============================================================
# V45 IK-resolved poses.  Generated by
# schneider_cell_description/scripts/resolve_poses.py with:
#   * lateral grasp two-pass IK; LATERAL_GRASP_OFFSET = 0.082 m
#     (V44 had 0.030 m which left the TCP 31 mm INSIDE the CAFI
#     footprint — appendage atravesando el CAFI — V45 places TCP
#     20 mm OUTSIDE the CAFI east face: no penetration).
#   * RELEASE_DZ = 0.020 m (CAFI dropped 2 cm into the cradle).
#   * V44 layout (bins right, vision left, smaller rivet cabin).
#   * per-joint mesa clearance > 5 mm at every pose.
# 19/19 PASS sub-mm position error.
# DO NOT hand-edit; regenerate by running resolve_poses.py.
# ============================================================
# V49 poses regenerated from scripts/resolve_poses.py with:
#   * PICK_CONVEYOR_TARGET_DX_WORLD = -0.03955 m applied to
#     APPROACH/PICK/LIFT_CONVEYOR (PICK now at world (1.268, 1.365,
#     1.086), 39.55 mm WEST of V48's (1.308, 1.365, 1.086)).
#   * BIN_REJ = (1.330, 0.700) (V48 had 0.580, off mesa south edge).
POSE_HOME                  = [+0.000000, +0.000000, +0.000000, +1.570796, -1.570796, +0.000000]
POSE_APPROACH_CONVEYOR     = [-1.888461, +1.476030, -1.605491, +1.634626, -1.618292, -1.888832]
POSE_PICK_CONVEYOR         = [-1.888433, +1.982371, -1.998296, +1.521084, -1.618295, -1.888793]
POSE_LIFT_CONVEYOR         = [-1.888463, +1.353483, -1.469901, +1.621583, -1.618292, -1.888834]
POSE_APPROACH_LOAD_FIXTURE = [-0.515798, +1.190992, -0.837014, +1.210330, -1.595452, -0.515262]
POSE_PLACE_LOAD_FIXTURE    = [-0.515811, +1.701508, -1.387685, +1.250481, -1.595452, -0.515275]
POSE_RELEASE_LOAD_FIXTURE  = [-0.515803, +1.623591, -1.322912, +1.263628, -1.595452, -0.515267]
POSE_RETREAT_LOAD_FIXTURE  = [-0.515773, +0.402427, +0.796378, +0.365522, -1.595454, -0.515237]
POSE_APPROACH_PICK_RIVETED = [-0.515773, +0.402427, +0.796378, +0.365522, -1.595454, -0.515237]
POSE_PICK_RIVETED          = [-0.515811, +0.386808, +1.347652, -0.170154, -1.595452, -0.515275]
POSE_LIFT_RIVETED          = [-0.517004, +0.198368, +1.284060, -0.176728, -1.602977, -0.521615]
POSE_APPROACH_VISION       = [+0.141158, +0.391580, +1.230516, -0.051784, -1.563766, +0.140985]
POSE_PLACE_VISION          = [+0.141165, +0.566146, +1.516833, -0.512667, -1.563767, +0.140993]
POSE_RELEASE_VISION        = [+0.141167, +0.523270, +1.487736, -0.440692, -1.563767, +0.140994]
POSE_RETREAT_VISION        = [+0.141158, +0.391580, +1.230518, -0.051786, -1.563766, +0.140984]
POSE_APPROACH_ACCEPT_BIN   = [+2.395914, +0.635978, +0.933268, -0.085211, -1.536879, +2.396536]
POSE_DROP_ACCEPT_BIN       = [+2.395902, +0.793033, +1.202875, -0.511876, -1.536877, +2.396523]
POSE_APPROACH_REJECT_BIN   = [+1.644097, -0.292349, +2.063516, -0.254041, -1.520927, +1.644186]
POSE_DROP_REJECT_BIN       = [+1.644100, +0.070862, +2.379413, -0.933147, -1.520926, +1.644189]

POSE_LIB = {
    "POSE_HOME": POSE_HOME,
    "POSE_APPROACH_CONVEYOR": POSE_APPROACH_CONVEYOR,
    "POSE_PICK_CONVEYOR": POSE_PICK_CONVEYOR,
    "POSE_LIFT_CONVEYOR": POSE_LIFT_CONVEYOR,
    "POSE_APPROACH_LOAD_FIXTURE": POSE_APPROACH_LOAD_FIXTURE,
    "POSE_PLACE_LOAD_FIXTURE": POSE_PLACE_LOAD_FIXTURE,
    "POSE_RELEASE_LOAD_FIXTURE": POSE_RELEASE_LOAD_FIXTURE,
    "POSE_RETREAT_LOAD_FIXTURE": POSE_RETREAT_LOAD_FIXTURE,
    "POSE_APPROACH_PICK_RIVETED": POSE_APPROACH_PICK_RIVETED,
    "POSE_PICK_RIVETED": POSE_PICK_RIVETED,
    "POSE_LIFT_RIVETED": POSE_LIFT_RIVETED,
    "POSE_APPROACH_VISION": POSE_APPROACH_VISION,
    "POSE_PLACE_VISION": POSE_PLACE_VISION,
    "POSE_RELEASE_VISION": POSE_RELEASE_VISION,
    "POSE_RETREAT_VISION": POSE_RETREAT_VISION,
    "POSE_APPROACH_ACCEPT_BIN": POSE_APPROACH_ACCEPT_BIN,
    "POSE_DROP_ACCEPT_BIN": POSE_DROP_ACCEPT_BIN,
    "POSE_APPROACH_REJECT_BIN": POSE_APPROACH_REJECT_BIN,
    "POSE_DROP_REJECT_BIN": POSE_DROP_REJECT_BIN,
}


# ============================================================
# TRAJECTORIES (now: approach -> pose -> grip wait -> retreat)
# ============================================================
TRAJ_PICK_CONV = [
    "POSE_APPROACH_CONVEYOR",
    "POSE_PICK_CONVEYOR",
    "GRIPPER_CLOSE_AND_WAIT",
    "POSE_LIFT_CONVEYOR",
]
# V29: every TRAJ_PLACE_* ends with POSE_HOME so the cobot ALWAYS
# returns to HOME after every delivery before the dispatcher decides
# the next action.  User V29 requirement F: "DESPUES DE ENTREGAR
# CUALQUIER PIEZA, EL COBOT REGRESA A HOME."
# V43: when PLACING the CAFI on a fixture, the gripper holds it 100 mm
# ABOVE the cradle base before opening.  The CAFI then falls under
# gravity (object_manager settling state) and lands cleanly on the seat.
# This replaces the V20..V42 sequence where the gripper went all the
# way down to the cradle, opened, and would visually "stick" the CAFI
# into the fixture body.
TRAJ_PLACE_OUTER = [
    "POSE_APPROACH_LOAD_FIXTURE",      # 120 mm above seat (transit)
    "POSE_RELEASE_LOAD_FIXTURE",       # V43: 100 mm above seat (release point)
    "GRIPPER_OPEN_AND_WAIT",            # release here -> object_manager settles
    "POSE_RETREAT_LOAD_FIXTURE",       # 120 mm above seat (transit)
    "POSE_HOME",                       # V29: forced return to HOME
]
TRAJ_PICK_RIVETED = [
    "POSE_APPROACH_PICK_RIVETED",
    "POSE_PICK_RIVETED",
    "GRIPPER_CLOSE_AND_WAIT",
    "POSE_LIFT_RIVETED",
]
TRAJ_PLACE_VISION = [
    "POSE_APPROACH_VISION",            # 120 mm above seat
    "POSE_RELEASE_VISION",             # V43: 100 mm above seat (release point)
    "GRIPPER_OPEN_AND_WAIT",            # release -> CAFI settles
    "POSE_RETREAT_VISION",
    "POSE_HOME",                       # V29: forced return to HOME
]
TRAJ_PLACE_ACCEPT = [
    "POSE_APPROACH_ACCEPT_BIN",
    "POSE_DROP_ACCEPT_BIN",
    "GRIPPER_OPEN_AND_WAIT",
    "POSE_APPROACH_ACCEPT_BIN",
    "POSE_HOME",                       # V29: forced return to HOME
]
TRAJ_PLACE_REJECT = [
    "POSE_APPROACH_REJECT_BIN",
    "POSE_DROP_REJECT_BIN",
    "GRIPPER_OPEN_AND_WAIT",
    "POSE_APPROACH_REJECT_BIN",
    "POSE_HOME",                       # V29: forced return to HOME
]
# V28: Missing in V27 - pick the CAFI back up from the vision fixture
# after the camera produces a verdict, BEFORE going to the bin.
# V27 went straight from INSPECT -> PLACE_BIN, but the CAFI was sitting
# at the vision station; the robot moved to the bin with an empty
# gripper and the CAFI never made it.
TRAJ_PICK_VISION = [
    "POSE_APPROACH_VISION",
    "POSE_PLACE_VISION",
    "GRIPPER_CLOSE_AND_WAIT",
    "POSE_RETREAT_VISION",
]
TRAJ_HOME = ["POSE_HOME"]


# ============================================================
# Motion timing
# ============================================================
TICK_HZ          = 50.0
# V42: slower, smoother motion.  V41 had JOINT_VEL_MAX=1.4 rad/s and
# SEG_DURATION_MIN=1.0 s which made pose-to-pose moves look snappy.
# The cosine interpolation already eases each segment, but with the
# top-down R_target IK some joint deltas approach 4 rad and the
# resulting visible velocity is jerky.  V42 tunes:
#   JOINT_VEL_MAX  1.4 -> 0.9 rad/s  (~36% slower)
#   SEG_DURATION_MIN 1.0 -> 1.5 s    (longer ease-in/out)
#   SEG_DURATION_MAX 4.0 -> 6.0 s    (allow longer for big-delta jumps)
JOINT_VEL_MAX    = 0.9          # rad/s cap per joint  (visible motion)
SEG_DURATION_MIN = 1.5          # at least 1.5 s per segment
SEG_DURATION_MAX = 6.0          # cap so abandoned segments don't hang
GRIPPER_WAIT_S   = 4.0          # max wait for grasp_confirmed / release_done
HOLD_AT_PICK_S   = 0.4          # extra dwell so the gripper has time to close


def clamp_joints(q):
    return [max(J_LIMIT_LOW[i], min(J_LIMIT_HIGH[i], q[i]))
            for i in range(6)]


def shortest_path_target(q_current, q_target):
    """V35: Re-wrap each joint target to the 2*pi-equivalent angle
    closest to q_current, clamped to the joint limits.  Eliminates
    spurious full-rotation segments where the IK-resolved pose differs
    from the current pose by ~360 deg even though the equivalent joint
    angle minus 2*pi (or plus 2*pi) is inside the joint limits and
    much closer in joint space.

    Example: q_current[3] = -3.10 rad, q_target[3] = +3.10 rad with
    joint limits (-pi, +pi).  Naive interp travels 6.20 rad
    (~355 deg).  Shortest path: target_equivalent = 3.10 - 2*pi =
    -3.18 rad (out of limits), or 3.10 rad (the same).  We therefore
    keep 3.10.  But for joints with wider limits, the wrap-around
    branch can land inside the limits and saves a full rotation."""
    out = []
    for i in range(6):
        cur = q_current[i]
        tgt = q_target[i]
        lo, hi = J_LIMIT_LOW[i], J_LIMIT_HIGH[i]
        # Candidate equivalents within +/- 2*pi of cur
        best = tgt
        best_d = abs(tgt - cur)
        for k in (-1, +1):
            cand = tgt + k * 2.0 * math.pi
            if lo <= cand <= hi:
                d = abs(cand - cur)
                if d < best_d:
                    best = cand
                    best_d = d
        out.append(max(lo, min(hi, best)))
    return out


def cosine_interp(t):
    return 0.5 * (1.0 - math.cos(math.pi * max(0.0, min(1.0, t))))


def joints_close(a, b, tol=0.005):
    return all(abs(a[i] - b[i]) <= tol for i in range(6))


class RobotController(object):

    def __init__(self):
        rospy.init_node("schneider_robot_controller", anonymous=False)

        # V39: spawn AT POSE_HOME = (0,0,0,+pi/2,-pi/2,0) so the cobot
        # immediately holds the real planta HOME pose (J4=+90, J5=-90).
        self.q_current = list(POSE_HOME)
        self.q_start   = list(POSE_HOME)
        self.q_target  = list(POSE_HOME)
        self.seg_t0    = 0.0
        self.seg_active = False
        self.seg_duration = SEG_DURATION_MIN

        # Trajectory queue
        self.traj_queue = []        # list of mixed: pose name | gripper op
        self.current_task = "idle"

        # Gripper wait state
        self.waiting_for = None     # None | "grasp" | "release"
        self.wait_t0 = 0.0

        # External signals
        self.grasp_confirmed = False
        self.release_done = False

        self.lock = threading.RLock()

        # Pubs
        self.pub_cobot_joints = rospy.Publisher(
            "/robot/cobot_joints", JointState, queue_size=2)
        self.pub_motion_done  = rospy.Publisher(
            "/robot/motion_done", Bool, queue_size=2)
        self.pub_busy         = rospy.Publisher(
            "/robot/busy", Bool, queue_size=1, latch=True)
        self.pub_task         = rospy.Publisher(
            "/robot/current_task", String, queue_size=1, latch=True)
        self.pub_grip_open    = rospy.Publisher(
            "/gripper/open_cmd",  Empty, queue_size=2)
        self.pub_grip_close   = rospy.Publisher(
            "/gripper/close_cmd", Empty, queue_size=2)

        # Subs
        rospy.Subscriber("/robot/request_pick_conveyor",
                         Empty, lambda m: self._enqueue("pick_conv",
                                                        TRAJ_PICK_CONV))
        rospy.Subscriber("/robot/request_place_fixture",
                         String, lambda m: self._enqueue("place_outer",
                                                         TRAJ_PLACE_OUTER))
        rospy.Subscriber("/robot/request_pick_riveted",
                         String, lambda m: self._enqueue("pick_riveted",
                                                         TRAJ_PICK_RIVETED))
        rospy.Subscriber("/robot/request_place_vision",
                         Empty, lambda m: self._enqueue("place_vision",
                                                        TRAJ_PLACE_VISION))
        # V28: missing topic - pick CAFI back up from vision after verdict
        rospy.Subscriber("/robot/request_pick_vision",
                         Empty, lambda m: self._enqueue("pick_vision",
                                                        TRAJ_PICK_VISION))
        rospy.Subscriber("/robot/request_place_accept_bin",
                         Empty, lambda m: self._enqueue("place_accept",
                                                        TRAJ_PLACE_ACCEPT))
        rospy.Subscriber("/robot/request_place_reject_bin",
                         Empty, lambda m: self._enqueue("place_reject",
                                                        TRAJ_PLACE_REJECT))
        rospy.Subscriber("/robot/request_home",
                         Empty, lambda m: self._enqueue("home", TRAJ_HOME))

        # Listen to gripper feedback so PICK can wait for grasp_confirmed
        rospy.Subscriber("/gripper/grasp_confirmed",
                         Bool, self._cb_grasp)
        rospy.Subscriber("/gripper/release_done",
                         Empty, self._cb_release)

        self.pub_busy.publish(Bool(data=False))
        self.pub_task.publish(String(data="idle"))
        rospy.loginfo("[CTRL] V25 robot_controller init - 17 IK-validated "
                      "poses (grasp_center at jaw-mid link Z=+0.025), "
                      "interpolated joint-space motion, geometric grasp "
                      "gating, gripper close emitted ONLY after reaching "
                      "PICK pose.")

    def _cb_grasp(self, m):
        v = bool(m.data)
        if v and not self.grasp_confirmed:
            rospy.loginfo("[CTRL] grasp_confirmed=True received from gripper_sim")
        self.grasp_confirmed = v

    def _cb_release(self, _m):
        rospy.loginfo("[CTRL] release_done received from gripper_sim")
        self.release_done = True

    # =========================================================
    # Trajectory enqueue
    # =========================================================
    def _enqueue(self, task_name, traj_steps):
        with self.lock:
            rospy.loginfo("[CTRL] request_%s received - enqueueing %d steps: "
                          "%s", task_name, len(traj_steps),
                          " -> ".join(traj_steps))
            self.traj_queue = list(traj_steps)
            self.current_task = task_name
            self.pub_task.publish(String(data=task_name))
            self.pub_busy.publish(Bool(data=True))
            self.pub_motion_done.publish(Bool(data=False))
            self.grasp_confirmed = False  # reset; gripper_sim will republish
            self.release_done = False
            rospy.loginfo("[CTRL] TRAJ_%s started (task=%s)",
                          task_name.upper(), task_name)
            self._start_next_step()

    def _start_next_step(self):
        if not self.traj_queue:
            self.seg_active = False
            self.waiting_for = None
            self.pub_busy.publish(Bool(data=False))
            self.pub_motion_done.publish(Bool(data=True))
            rospy.loginfo("[CTRL] TRAJ_%s completed -> /robot/motion_done=True",
                          self.current_task.upper())
            self.current_task = "idle"
            self.pub_task.publish(String(data="idle"))
            return

        step = self.traj_queue.pop(0)

        if step == "GRIPPER_CLOSE_AND_WAIT":
            self.pub_grip_close.publish(Empty())
            self.grasp_confirmed = False
            self.waiting_for = "grasp"
            self.wait_t0 = rospy.Time.now().to_sec()
            rospy.loginfo("[CTRL] GRIPPER_CLOSE emitted at PICK pose "
                          "(task=%s) -> waiting for /gripper/grasp_confirmed "
                          "(timeout %.1fs)", self.current_task, GRIPPER_WAIT_S)
            return

        if step == "GRIPPER_OPEN_AND_WAIT":
            self.pub_grip_open.publish(Empty())
            self.release_done = False
            self.waiting_for = "release"
            self.wait_t0 = rospy.Time.now().to_sec()
            rospy.loginfo("[CTRL] GRIPPER_OPEN emitted at PLACE pose "
                          "(task=%s) -> waiting for /gripper/release_done "
                          "(timeout %.1fs)", self.current_task, GRIPPER_WAIT_S)
            return

        # Pose target
        if step not in POSE_LIB:
            rospy.logerr("[CTRL] unknown step %s -> skip", step)
            self._start_next_step()
            return
        # V35: pick the 2*pi-equivalent target closest to q_current so
        # joints with wide limits do not take the long way round.  See
        # shortest_path_target() docstring.
        target = shortest_path_target(self.q_current,
                                      clamp_joints(POSE_LIB[step]))
        self.q_start  = list(self.q_current)
        self.q_target = list(target)
        self.seg_t0   = rospy.Time.now().to_sec()
        self.seg_active = True
        max_delta = max(abs(self.q_target[i] - self.q_start[i])
                        for i in range(6))
        # duration = max_delta / vel, capped
        self.seg_duration = max(SEG_DURATION_MIN,
                                min(SEG_DURATION_MAX,
                                    max_delta / JOINT_VEL_MAX))
        rospy.loginfo("[CTRL] segment -> %s (delta_max=%.3f rad dur=%.2fs)",
                      step, max_delta, self.seg_duration)

    # =========================================================
    # TICK
    # =========================================================
    def tick(self):
        with self.lock:
            now = rospy.Time.now().to_sec()

            # 1. Active joint-space segment
            if self.seg_active:
                t = (now - self.seg_t0) / self.seg_duration
                if t >= 1.0:
                    t = 1.0
                    self.seg_active = False
                eased = cosine_interp(t)
                for i in range(6):
                    self.q_current[i] = (self.q_start[i] +
                                         (self.q_target[i] - self.q_start[i])
                                         * eased)
                if not self.seg_active:
                    # Dwell briefly so the gripper can act on the new pose
                    rospy.Timer(rospy.Duration(HOLD_AT_PICK_S),
                                lambda evt: self._start_next_step(),
                                oneshot=True)

            # 2. Waiting for gripper event
            if self.waiting_for == "grasp":
                if self.grasp_confirmed:
                    rospy.loginfo("[CTRL] grasp received -> advance trajectory")
                    self.waiting_for = None
                    self._start_next_step()
                elif now - self.wait_t0 > GRIPPER_WAIT_S:
                    rospy.logwarn("[CTRL] grasp wait TIMED OUT after %.1fs "
                                  "(task=%s). Advancing without grasp - "
                                  "state_manager watchdog will catch this.",
                                  GRIPPER_WAIT_S, self.current_task)
                    self.waiting_for = None
                    self._start_next_step()
            elif self.waiting_for == "release":
                if self.release_done:
                    rospy.loginfo("[CTRL] release received -> advance trajectory")
                    self.waiting_for = None
                    self._start_next_step()
                elif now - self.wait_t0 > GRIPPER_WAIT_S:
                    rospy.logwarn("[CTRL] release wait TIMED OUT after %.1fs "
                                  "(task=%s). Advancing.",
                                  GRIPPER_WAIT_S, self.current_task)
                    self.waiting_for = None
                    self._start_next_step()

            # 3. Publish joint state every tick - RViz needs continuous flow
            js = JointState()
            js.header.stamp = rospy.Time.now()
            js.name = COBOT_JOINTS
            js.position = list(self.q_current)
            self.pub_cobot_joints.publish(js)

    def run(self):
        rate = rospy.Rate(TICK_HZ)
        while not rospy.is_shutdown():
            self.tick()
            rate.sleep()


if __name__ == "__main__":
    try:
        RobotController().run()
    except rospy.ROSInterruptException:
        pass
